json.id student.id
json.first_name student.first_name
json.email student.email
json.phone student.phone
json.bio student.bio
json.linkedin student.linkedin
json.twitter student.twitter
json.personal_blog student.personal_blog
json.online_resume student.online_resume
json.github student.github
json.photo student.photo
json.capstones student.capstones
json.educations student.educations
json.experiences student.experiences
json.skills student.skills
